FROM golang:latest AS builder
RUN \
  git clone --depth 1 https://github.com/junegunn/fzf.git  \
  && cd fzf \
  && make release && make install && pwd

FROM ubuntu:latest
COPY --from=builder  /go/fzf/bin/fzf /usr/local/bin

#  && ./install --all \

#FROM alpine:latest
#LABEL maintainer "Mario Tao <cloudqq@gmail.com>""




# COPY star-dict-installer.sh /root
# ENV http_proxy 10.3.4.4:1088
# ENV https_proxy 10.3.4.4:108
# RUN  cd /root && sh star-dict-installer.sh

CMD ["bash"]

