ARG VERSION=latest
FROM ubuntu:$VERSION

MAINTAINER cloudqq <cloudqq@gmail.com>

# Fix "Couldn't register with accessibility bus" error message
ENV NO_AT_BRIDGE=1

ENV DEBIAN_FRONTEND noninteractive

RUN sed --in-place --regexp-extended "s/archive\.ubuntu/azure\.archive\.ubuntu/g" /etc/apt/sources.list \
  && echo 'APT::Get::Assume-Yes "true";' >> /etc/apt/apt.conf \
  &&  echo 'APT::Get::Install-Recommends "false";' >> /etc/apt/apt.conf \
  && echo 'APT::Get::Install-Suggests "false";' >> /etc/apt/apt.conf \
  && apt-get update && apt-get install curl git

COPY star-dict-installer.sh /root
ENV http_proxy 10.3.4.4:1088
ENV https_proxy 10.3.4.4:108
RUN  cd /root && sh star-dict-installer.sh

CMD ["bash"]

