ARG VERSION=latest
FROM ubuntu:$VERSION

MAINTAINER cloudqq <cloudqq@gmail.com>

# Fix "Couldn't register with accessibility bus" error message
ENV NO_AT_BRIDGE=1

ENV DEBIAN_FRONTEND noninteractive

RUN sed --in-place --regexp-extended "s/archive\.ubuntu/azure\.archive\.ubuntu/g" /etc/apt/sources.list \
  && echo 'APT::Get::Assume-Yes "true";' >> /etc/apt/apt.conf \
  && apt-get update && apt-get install software-properties-common apt-utils  \
  && apt-add-repository ppa:kelleyk/emacs \
  && apt-get update \
  && apt-get install \
  bash \
  build-essential \
  emacs26 \
  emacs26-el

CMD ["bash"]

