ARG VERSION=latest
FROM rust:$VERSION AS builder

RUN \
  git clone --depth 1 https://github.com/BurntSushi/ripgrep \
  && cd ripgrep \
  && cargo build --release \
  && ./target/release/rg --version \
  && cp ./target/release/rg /usr/local/bin

FROM ubuntu:latest
COPY --from=builder /usr/local/bin /usr/local/bin




# COPY star-dict-installer.sh /root
# ENV http_proxy 10.3.4.4:1088
# ENV https_proxy 10.3.4.4:108
# RUN  cd /root && sh star-dict-installer.sh

CMD ["bash"]

