#ARG VERSION=latest
FROM docker:ding

MAINTAINER cloudqq <cloudqq@gmail.com>

# Fix "Couldn't register with accessibility bus" error message
#ENV NO_AT_BRIDGE=1

RUN apk update \
  && apk add --virtual build-dependencies \
  build-base \
  gcc \
  wget \
  git \
  bash \
&& rm -rf /var/cache/apk/*

#ENV DEBIAN_FRONTEND noninteractive

# basic stuff


CMD ["bash", "sh"]
